### ISSUE TITLE
Different Robot Radius

### ISSUE THREAD

**Issue by bektaskemal** [NKU-MobFly-Robotics/local-planning-benchmark#11]
Hi,

I want to use this benchmark with another bigger robot because I trained my planner for it.
But I think these worlds are not suitable for it. Did you consider this problem or do you have any suggestions about it?

**Comment by nkuwenjian** [comment]
Hi,

We are sorry that we designed the scenarios with reference to the size of the indoor mobile robot pioneer 3-DX, so these scenarios such as the narrow maze may not be suitable for large-sized outdoor mobile robots, e.g., husky.

In the future, we will build simulation scenarios for field robots, such as underground caves and mines. Currently, please consider using our robot model to train your planner. 

Best, 

Jian Wen
2021/9/6
